// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetConfig():Promise<backend.Config>;

export function GetConfigPath():Promise<string>;

export function GetProcessLogs(arg1:string,arg2:string):Promise<Array<string>>;

export function GetProcessRunning(arg1:string,arg2:string):Promise<boolean>;

export function KillProcess(arg1:string,arg2:string):Promise<void>;

export function OpenInEditor(arg1:string,arg2:string):Promise<void>;

export function ReadConfigFile():Promise<string>;

export function ReadDir(arg1:string):Promise<Array<backend.FileItem>>;

export function SaveConfig(arg1:backend.Config):Promise<void>;

export function ScanWorkspace(arg1:string):Promise<Array<backend.Project>>;

export function SearchWorkspace(arg1:string,arg2:string,arg3:string):Promise<Array<backend.SearchResult>>;

export function SelectDirectory():Promise<string>;

export function StartProcess(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function WriteConfigFile(arg1:string):Promise<void>;
