// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetProcessLogs(arg1, arg2) {
  return window['go']['main']['App']['GetProcessLogs'](arg1, arg2);
}

export function GetProcessRunning(arg1, arg2) {
  return window['go']['main']['App']['GetProcessRunning'](arg1, arg2);
}

export function KillProcess(arg1, arg2) {
  return window['go']['main']['App']['KillProcess'](arg1, arg2);
}

export function OpenInEditor(arg1, arg2) {
  return window['go']['main']['App']['OpenInEditor'](arg1, arg2);
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanWorkspace(arg1) {
  return window['go']['main']['App']['ScanWorkspace'](arg1);
}

export function SearchWorkspace(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchWorkspace'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartProcess(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartProcess'](arg1, arg2, arg3, arg4);
}
